name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Emscripten
      uses: lovasoa/setup-emscripten@v1
      with:
        emscripten-version:
    - name: build
      run: |
        make -j
        zip --junk-paths jsdrawterm.zip *.html *.js *.wasm *.jpg README.md
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Build"
        files: |
          jsdrawterm.zip
